services:
  mysql:
    image: mysql:8.0
    container_name: oulib-db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: oulib
      MYSQL_USER: oulib
      MYSQL_PASSWORD: oulib123
    volumes:
      - ./volumes/mysql:/var/lib/mysql
    ports:
      - "3307:3306"
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h localhost -uroot -proot"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:alpine
    container_name: oulib-redis
    ports:
      - "6379:6379"
    restart: unless-stopped
    volumes:
      - ./volumes/redis/data:/data